---
collections:
  - name: redhat_cop.controller_configuration
  - name: redhat_cop.ah_configuration
  - name: redhat_cop.ee_utilities
  - name: redhat_cop.aap_utilities
  - name: containers.podman
  - name: ansible.controller
  - name: awx.awx
...
