---
- name: Playbook to configure ansible controller post installation
  hosts: all
  vars_files:
    - "../vaults/{{ env }}.yml"
  connection: local
  tasks:
    - name: Sleep for 300 seconds and allow awx to come up.
      ansible.builtin.wait_for:
        timeout: 300
      delegate_to: localhost

    - name: Wait for Controller to come up
      ansible.builtin.uri:
        url: "https://{{ controller_hostname }}/api/v2/ping"
        status_code: 200
        validate_certs: "{{ controller_validate_certs }}"
      register: result
      until: result.status == 200
      retries: 10
      delay: 30
      ignore_errors: true

    - name: "Show result of ping"
      ansible.builtin.debug:
        var: result
...
