objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory: {}
  lookup:
    ah_api:
      description: Search the API for objects
      name: ah_api
      version_added: null
  module:
    ah_approval:
      description: Approve a collection in Automation Hub.
      name: ah_approval
      namespace: ''
      version_added: null
    ah_build:
      description: Build a collection tar.
      name: ah_build
      namespace: ''
      version_added: null
    ah_collection:
      description: update, or destroy Automation Hub Collections.
      name: ah_collection
      namespace: ''
      version_added: null
    ah_collection_upload:
      description: Upload a collection artifact to Automation Hub.
      name: ah_collection_upload
      namespace: ''
      version_added: null
    ah_ee_image:
      description: Manage private automation hub execution environment images
      name: ah_ee_image
      namespace: ''
      version_added: 0.4.3
    ah_ee_namespace:
      description: Manage private automation hub execution environment namespaces
      name: ah_ee_namespace
      namespace: ''
      version_added: 0.4.3
    ah_ee_registry:
      description: Manage private automation hub execution environment remote registries.
      name: ah_ee_registry
      namespace: ''
      version_added: 0.7.0
    ah_ee_registry_index:
      description: Initiate an execution environment registry indexing.
      name: ah_ee_registry_index
      namespace: ''
      version_added: null
    ah_ee_registry_sync:
      description: Initiate an execution environment registry sync.
      name: ah_ee_registry_sync
      namespace: ''
      version_added: null
    ah_ee_repository:
      description: Manage private automation hub execution environment repositories/containers
      name: ah_ee_repository
      namespace: ''
      version_added: 0.4.3
    ah_ee_repository_sync:
      description: Initiate an execution environment repository sync.
      name: ah_ee_repository_sync
      namespace: ''
      version_added: null
    ah_group:
      description: Manage private automation hub user groups
      name: ah_group
      namespace: ''
      version_added: 0.4.3
    ah_group_perm:
      description: Manage group permissions
      name: ah_group_perm
      namespace: ''
      version_added: 0.4.3
    ah_namespace:
      description: create, update, or destroy Automation Hub Namespace.
      name: ah_namespace
      namespace: ''
      version_added: null
    ah_repository:
      description: Configure a repository.
      name: ah_repository
      namespace: ''
      version_added: null
    ah_repository_sync:
      description: Configure a repository.
      name: ah_repository_sync
      namespace: ''
      version_added: null
    ah_token:
      description: create, update, or destroy Automation Hub tokens.
      name: ah_token
      namespace: ''
      version_added: '2.10'
    ah_user:
      description: Manage private automation hub users
      name: ah_user
      namespace: ''
      version_added: 0.4.3
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 0.9.2-beta
