---
ee_list:
  - ee_name: ee_tools
    bindep:
      - unzip
    python:
      - ansible-lint
      - jmespath
      - netaddr
    collections:
      - name: awx.awx
      - name: infra.tower_utilities
...
