---
controller_templates_all:
  - name: aap_config
    project: config_as_code
    job_type: run
    playbook: playbooks/aap_config.yml
    inventory: config_as_code
    execution_environment: supported
    concurrent_jobs_enabled: false
    ask_variables_on_launch: true
    limit: "{{ env }}"
    verbosity: 0
    credentials:
      - aap_admin
      - hub_token_user
      - vault
    extra_vars:
      # for debugging errors with creds change to false
      controller_configuration_credentials_secure_logging: true

  - name: build_execution_environments
    project: config_as_code
    job_type: run
    playbook: playbooks/build_ee.yml
    inventory: config_as_code
    execution_environment: supported
    concurrent_jobs_enabled: false
    verbosity: 0
    credentials:
      - root
      - hub_admin_user_pass
    labels:
      - EE

  - name: build_custom_collections
    project: config_as_code
    job_type: run
    playbook: playbooks/custom_collection.yml
    inventory: config_as_code
    execution_environment: supported
    concurrent_jobs_enabled: false
    limit: "{{ env }}"
    verbosity: 0
    credentials:
      - root
      - hub_token_user

  - name: console_token_refresh
    project: config_as_code
    job_type: run
    playbook: playbooks/console_token_refresh.yml
    inventory: config_as_code
    execution_environment: minimal
    concurrent_jobs_enabled: false
    limit: "{{ env }}"
    verbosity: 0
    credentials:
      - vault

  - name: collection_sync
    project: config_as_code
    job_type: run
    playbook: playbooks/sync_collections.yml
    inventory: config_as_code
    execution_environment: minimal
    concurrent_jobs_enabled: false
    limit: "{{ env }}"
    verbosity: 0
    credentials:
      - hub_token_user
      - vault
...
