---
- name: Publish custom collection
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Include common vars
      ansible.builtin.include_vars:
        dir: ../config/all
        extensions:
          - 'yml'

    - name: Include env vars
      ansible.builtin.include_vars:
        dir: "../config/{{ env }}"
        extensions:
          - 'yml'

    - name: Include namespace role
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_namespace

    - name: Include publish role
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_publish
...
