---
- name: Playbook to configure event driven ansible controller post installation
  hosts: all
  vars_files:
    - "../vaults/{{ env }}.yml"
  connection: local
  tasks:
    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.eda_configuration.dispatch

...
