---
name: ansible-lint
permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run ansible-lint
        uses: ansible/ansible-lint@5fac056c45595896c973fbde871f01f6cb14d74c # main
        # optional (see below):
        with:
          # args: ""
          setup_python: "true"
          # working_directory: ""
          requirements_file: ".github/requirements.yml"
