---
# name: Ansible Lint # feel free to pick your own name
# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v2
#       - name: Add cloud and galaxy tokens
#         run: echo -e "${{ secrets.galaxy_token }}" >> ansible.cfg
#       - name: Install ansible-lint
#         run: pip3 install ansible-core ansible-lint yamllint
#       - name: Install Collections
#         run: ansible-galaxy collection install -f -r collections/requirements.yml
#       - name: Lint Ansible Playbook
#         run: ansible-lint --profile=production
#       # - name: Run ansible-lint
#       #   uses: ansible-community/ansible-lint-action@main
#       #   # optional:
#       #   # with:
#       #   #   path: "playbooks/"  # <-- only one value is allowed

name: Ansible Lint

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Collections
        run: |
          echo -e "${{ secrets.galaxy_token }}" >> ansible.cfg
          ansible-galaxy collection install -f -r .github/requirements.yml
      - name: ansible-lint
        uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
        with:
          target: .
...
